services:
  rsp-wip:
    build:
      context: ../..
      target: rsp-eth-proofs
      ssh:
        - default
    env_file: .env
    depends_on:
      - moongate-wip
    restart: unless-stopped
  moongate-wip:
    image: moongate-wip
    runtime: nvidia
    deploy:
      resources:
          reservations:
            devices:
              - driver: nvidia
                capabilities: [gpu]
    restart: unless-stopped