[workspace]
[package]
name = "rsp-guest"
description = ""
version.workspace = true
edition.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true

[dependencies]
bincode = "1.3.3"

# workspace
rsp-guest-executor.workspace = true

# sp1
sp1-zkvm = { git = "https://github.com/succinctlabs/sp1.git" }
