[workspace.package]
[package]
name = "rsp-guest"
description = ""
edition = "2021"

[dependencies]
bincode = "1.3.3"

# workspace
rsp-guest-executor = { path = "../../crates/executor/guest" }

# sp1
sp1-zkvm = "1.0.1"

[patch.crates-io]
# alloy-eips = { path = "../alloy/crates/eips" }
# alloy-serde = { path = "../alloy/crates/serde" }
alloy-eips = { git = "https://github.com/jtguibas/alloy.git", branch = "john/rsp-8e9e6ac" }
alloy-serde = { git = "https://github.com/jtguibas/alloy.git", branch = "john/rsp-8e9e6ac" }
tiny-keccak = { git = "https://github.com/sp1-patches/tiny-keccak", branch = "patch-v2.0.2" }
