[package]
name = "rsp-client-op"
description = ""
edition = "2021"

[dependencies]
bincode = "1.3.3"

# workspace
rsp-client-executor = { path = "../../crates/executor/client" }

# sp1
sp1-zkvm = "4.0.0"

# Statically turns off logging
log = { version = "0.4", features = ["max_level_off", "release_max_level_off"] }
tracing = { version = "0.1", features = ["max_level_off", "release_max_level_off"] }
